### PR TITLE
Refreshing our placeholder for TS Federation

### PR DESCRIPTION
**Pull request by fournet**
Cleaning up the Federation section, still TBD.

### CODE REVIEW

**Review by henkbirkholz — APPROVED** [review]
lgtm, any objections? still in early stage

**Comment by henkbirkholz** [comment]
Also:
> *** Run 'make fix-lint' to automatically fix some errors

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
Linting errors need to be addressed. @henkbirkholz if this blocks publishing / merging perhaps we can merge and then fix?

**Comment by henkbirkholz** [comment]
> Linting errors need to be addressed. @henkbirkholz if this blocks publishing / merging perhaps we can merge and then fix?

Yes, I can fix the lint after merging. If this would be a branch and not a fork, I could do it here more easily.

**Pull request merged**
