### PR TITLE
Replace TS with SCITT Instance and other nit fixes

### PR DESCRIPTION
**Pull request by SteveLasker**
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by fournet** [comment]
I still prefer TS to SCITT instance, as in this architecture it refers specifically to the core transparency service for SCITT. Perhaps SCITTS if TS is too overloaded?

**Review by henkbirkholz — COMMENTED** [review]
Postponed the proposal for discussion at IETF 115

**Comment by yogeshbdeshpande** [comment]
Same comment as Cedric:

I prefer Transparency Service, which is more logical term.

SCITT Instance feels more like Implementation aspect!

@SteveLasker Shall we close this PR then, without merging?

**Comment by rjb4standards** [comment]
+1 Transparency Service

**Comment by OR13** [comment]
+1 to Transparency Service

**Comment by SteveLasker** [comment]
After IETF, we've landed one set of terminology that SCITT is a set of standards and protocols, so changing this to SCITT Instance does feel wrong.

We also discussed not using acronyms, so would we expand TS to Transparency Service?

We also use the terminology Registry, interchangeably with TS/Transparency Service See [here](https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/pull/30/files#diff-1812d688e87fa061cf31763fd9aa9d2426e327c292d4b3f03d604f7975220b79L518)

I'm converting this to a draft, with (#38) to define what we should call an instance of the SCITT standards.

**Comment by SteveLasker** [comment]
Closing as this became issue #38

**Pull request closed without merging**
